# Generated by Django 4.0 on 2021-12-28 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEspecialidade', models.CharField(max_length=30)),
                ('cbos', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoProcedimento', models.TextField()),
                ('tipoProcedimento', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMedico', models.CharField(max_length=50)),
                ('crm', models.CharField(max_length=50)),
                ('datanascMedico', models.DateField(verbose_name='Bith Date')),
                ('especialidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.especialidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enderecoAtendimento', models.CharField(max_length=250)),
                ('especialidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.especialidade')),
                ('nomeMedico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.medico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAtend', models.DateTimeField(default=django.utils.timezone.now)),
                ('enderecoAtendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.localatendimento')),
                ('nomeBeneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.beneficiario')),
                ('nomeEspecialidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.especialidade')),
                ('nomeMedico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.medico')),
                ('tipoProcedimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.procedimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
