# Generated by Django 4.0 on 2021-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_beneficiario_datanascbeneficiario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.ManyToManyField(to='items.Especialidade'),
        ),
    ]
