# Generated by Django 4.0 on 2021-12-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_medico_especialidade_medico_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.especialidade'),
        ),
    ]
